debug: false
config_gui_shuffle_interval: 10 #20L = 1 second | DON'T INCLUDE THE 'L' AT THE END
recipe:
       - AIR
       - DIAMOND
       - AIR
       - DIAMOND
       - NETHER_STAR
       - DIAMOND
       - AIR
       - DIAMOND
       - AIR
